homebrew_packages:
- autoconf
- autojump
- automake
- awscli
- cloc
- coreutils
- cowsay
- enchant
- exiftool
- fd
- fdupes
- ffmpeg
- freetype
- fswatch
- gdal
- gdbm
- git
- git-delta
- github/gh/gh
- goaccess
- gpg
- graphicsmagick
- heroku/brew/heroku
- hyperfine
- inetutils
- jhead
- jpeg
- jpegoptim
- jq
- lesspipe
- libevent
- libmemcached
- libpng
- libtool
- libyaml
- memcached
- myrepos
- ncdu
- nginx
- nvm
- openssl
- ossp-uuid
- pandoc
- parallel
- percona-toolkit
- pkg-config
- pngcrush
- postgresql
- pre-commit
- pwgen
- pyenv
- python
- qpdf
- readline
- rsync
- rtmpdump
- sd
- shellcheck
- sqlite
- starship
- swig
- tree
- watch
- watchman
- wget
- xz
- zlib
- zsh-completions

homebrew_cask_packages:
- '0xed'
- anki
- calibre
- discord
- docker
- evernote
- firefox
- homebrew/cask-fonts/font-ubuntu-mono-nerd-font
- franz
- iterm2
- istat-menus
- java
- karabiner-elements
- keyboard-maestro
- mactex
- mplayerx
- paintbrush
- rectangle
- rescuetime
- skim
- skype
- soundflower
- steam
- sublime-text
- tableplus
- unshaky
- vagrant
- virtualbox
- vlc

pyenv_python_versions:
# In precedence order
- 3.9.9
- 3.8.12
- 3.7.11
- 3.6.13
- 3.10.0
- pypy3.7-7.3.4

pip_packages:
- black
- boto
- boto3
- build
- csvkit
- flake8
- httpie
- ipdb
- ipython
- lifelogger
- pygments
- pythonpy
- python-language-server
- pyyaml
- requests
- s3cmd
- tox
- twine
- youtube-dl
- virtualenv
- wheel

gem_packages:
- jekyll
- jekyll-tagging
