homebrew_packages:
- atuin
- autoconf
- autojump
- automake
- awscli
- bat
- bettertouchtool
- btop
- coreutils
- enchant
- exiftool
- fd
- fdupes
- ffmpeg
- freetype
- fzf
- gdal
- gdbm
- gh
- git
- git-delta
- goaccess
- gpg
- graphviz
- heroku/brew/heroku
- hyperfine
- imagemagick
- inetutils
- jhead
- jpeg
- jpegoptim
- jq
- just
- less
- lesspipe
- libevent
- libmemcached
- libpng
- libtool
- libyaml
- lychee
- maccy
- memcached
- mise
- myrepos
- ncdu
- openssl
- ossp-uuid
- pandoc
- parallel
- percona-toolkit
- pkg-config
- postgresql@17
- qpdf
- readline
- rg
- rsync
- sd
- shellcheck
- sqlite
- starship
- tokei
- tmux
- tree
- typos-cli
- uv
- watch
- wget
- xz
- zed
- zlib
- zsh-completions
- zsh-autosuggestions
- zsh-history-substring-search
- zsh-syntax-highlighting

homebrew_cask_packages:
- anki
- audacity
- calibre
- discord
- docker
- evernote
- firefox
- font-ubuntu-mono-nerd-font
- google-earth-pro
- inkscape
- iterm2
- java
- karabiner-elements
- keyboard-maestro
- mactex
- stats
- steam
- tableplus
- vlc

uv_tools:
- name: black
- name: build
- name: flake8
- name: httpie
- name: ipython
- name: pre-commit
  with:
  - pre-commit-uv
- name: ruff
- name: tox
  with:
  - tox-uv
- name: ty
- name: yt-dlp

cargo_packages:
- cargo-cache
- oxipng
