homebrew_packages:
- autoconf
- autojump
- automake
- awscli
- cloc
- coreutils
- cowsay
- enchant
- exiftool
- fd
- fdupes
- ffmpeg
- freetype
- fswatch
- fzf
- gdal
- gdbm
- git
- git-delta
- github/gh/gh
- goaccess
- gpg
- graphicsmagick
- heroku/brew/heroku
- hyperfine
- inetutils
- jhead
- jpeg
- jpegoptim
- jq
- lesspipe
- libevent
- libmemcached
- libpng
- libtool
- libyaml
- memcached
- myrepos
- ncdu
- nginx
- nvm
- openssl
- ossp-uuid
- pandoc
- parallel
- percona-toolkit
- pkg-config
- postgresql
- pre-commit
- pwgen
- pyenv
- python
- qpdf
- readline
- rg
- rsync
- rtmpdump
- sd
- shellcheck
- sqlite
- starship
- swig
- tmux
- tree
- watch
- watchman
- wget
- xz
- zlib
- zsh-completions
- zsh-autosuggestions
- zsh-history-substring-search
- zsh-syntax-highlighting

homebrew_cask_packages:
- anki
- calibre
- discord
- docker
- evernote
- firefox
- homebrew/cask-fonts/font-ubuntu-mono-nerd-font
- franz
- iterm2
- istat-menus
- java
- karabiner-elements
- keyboard-maestro
- mactex
- mplayerx
- paintbrush
- rectangle
- skim
- skype
- steam
- sublime-text
- tableplus
- vagrant
- vlc

pyenv_python_versions:
# In precedence order
- 3.11.2
- 3.10.10
- 3.9.16
- 3.8.16
- 3.7.16
- 3.12.0a6
- pypy3.9-7.3.9

pip_packages:
- black
- boto
- boto3
- build
- csvkit
- flake8
- httpie
- ipdb
- ipython
- lifelogger
- poetry
- pre-commit
- pygments
- pythonpy
- python-language-server
- pyyaml
- requests
- s3cmd
- tox
- twine
- youtube-dl
- virtualenv
- wheel
