homebrew_taps: []

homebrew_package_removals: []

homebrew_packages:
- autoconf
- autojump
- automake
- bazaar
- cloc
- coreutils
- cowsay
- exiftool
- fdupes
- ffmpeg
- freetype
- fswatch
- gdal
- gdbm
- git
- gpg
- graphicsmagick
- hub
- imagemagick
- inetutils
- jhead
- jpeg
- jpegoptim
- jq
- lesspipe
- libevent
- libmemcached
- libpng
- libtool
- libyaml
- memcached
- ncdu
- nvm
- openssl
- ossp-uuid
- pandoc
- parallel
- percona-toolkit
- pkg-config
- pngcrush
- postgresql
- pwgen
- pyenv
- pypy
- python
- qpdf
- readline
- rsync
- rtmpdump
- ruby
- ruby-build
- ruby-install
- shellcheck
- sqlite
- swig
- tor
- tree
- watch
- wget
- xz
- yubikey-personalization
- zlib
- zsh-completions

homebrew_cask_packages:
- '0xed'
- alfred
- anki
- arq
- bitbar
- calibre
- dash
- disk-inventory-x
- docker
- evernote
- firefox
- font-roboto-mono
- font-ubuntumono-nerd-font
- franz
- google-chrome
- inkscape
- iterm2
- java
- karabiner-elements
- keyboard-maestro
- mactex
- mplayerx
- paintbrush
- playonmac
- rescuetime
- sequel-pro
- silverlight
- skim
- skype
- soundcleod
- soundflower
- steam
- sublime-text
- texmaker
- unshaky
- vagrant
- virtualbox
- vlc
- wireshark
- xquartz

pyenv_python_versions:
# In precedence order
- 3.7.4
- 3.6.9
- 3.5.7
- 2.7.16
- 3.8.0
- pypy3.6-7.1.1
- pypy2.7-7.1.1

pip_packages:
- awscli
- boto
- boto3
- csvkit
- ec2-ssh
- flake8
- httpie
- ipdb
- ipython
- lifelogger
- pipenv
- pygments
- pythonpy
- pyyaml
- requests
- s3cmd
- six
- tox
- twine
- virtualenvwrapper
- youtube-dl

gem_packages:
- jekyll
- jekyll-tagging
