homebrew_taps: []

homebrew_package_removals: []

homebrew_packages:
- autoconf
- autojump
- automake
- bazaar
- cloc
- coreutils
- cowsay
- exiftool
- fdupes
- ffmpeg
- freetype
- fswatch
- gdbm
- git
- gpg
- graphicsmagick
- hub
- imagemagick
- jhead
- jpeg
- jpegoptim
- jq
- lesspipe
- libevent
- libmemcached
- libpng
- libtool
- libyaml
- memcached
- ncdu
- node
- openssl
- ossp-uuid
- pandoc
- percona-toolkit
- pkg-config
- pngcrush
- postgresql
- pwgen
- pypy
- python
- python@2
- qpdf
- readline
- rsync
- rtmpdump
- ruby
- ruby-build
- ruby-install
- shellcheck
- sqlite
- swig
- telnet
- tor
- tree
- watch
- wget
- xz
- yubikey-personalization
- zsh-completions

homebrew_cask_packages:
- alfred
- anki
- arq
- bitbar
- calibre
- colloquy
- dash
- disk-inventory-x
- evernote
- firefox
- font-ubuntumono-nerd-font
- franz
- google-chrome
- inkscape
- iterm2
- java
- karabiner-elements
- keyboard-maestro
- mactex
- mplayerx
- paintbrush
- playonmac
- rescuetime
- sequel-pro
- silverlight
- skim
- skype
- soundcleod
- soundflower
- steam
- sublime-text
- texmaker
- vagrant
- virtualbox
- vlc
- wireshark
- xquartz

pip_packages:
- awscli
- boto
- boto3
- csvkit
- ec2-ssh
- flake8
- ipdb
- ipython
- lifelogger
- multilint
- pip-tools
- pipenv
- pygments
- pythonpy
- pyyaml
- requests
- six
- tox
- twine
- virtualenvwrapper
- youtube-dl

gem_packages:
- jekyll
- jekyll-tagging
