homebrew_packages:
- autoconf
- autojump
- automake
- awscli
- btop
- cloc
- coreutils
- enchant
- exiftool
- fd
- fdupes
- ffmpeg
- freetype
- fswatch
- fzf
- gdal
- gdbm
- gh
- git
- git-delta
- goaccess
- gpg
- graphicsmagick
- heroku/brew/heroku
- hyperfine
- inetutils
- jhead
- jpeg
- jpegoptim
- jq
- lesspipe
- libevent
- libmemcached
- libpng
- libtool
- libyaml
- memcached
- mise
- myrepos
- ncdu
- nginx
- openssl
- ossp-uuid
- pandoc
- parallel
- percona-toolkit
- pkg-config
- postgresql@16
- pre-commit
- pwgen
- python
- qpdf
- readline
- rg
- rsync
- rtmpdump
- sd
- shellcheck
- sqlite
- starship
- swig
- tmux
- tree
- uv
- watch
- watchman
- wget
- xz
- zlib
- zsh-completions
- zsh-autosuggestions
- zsh-history-substring-search
- zsh-syntax-highlighting

homebrew_cask_packages:
- anki
- calibre
- discord
- docker
- evernote
- firefox
- font-ubuntu-mono-nerd-font
- google-earth-pro
- iterm2
- istat-menus
- java
- karabiner-elements
- keyboard-maestro
- mactex
- rectangle
- skype
- steam
- sublime-text
- tableplus
- vlc

uv_tools:
- name: black
- name: build
- name: flake8
- name: httpie
- name: ipython
- name: pre-commit
  with:
  - pre-commit-uv
- name: tox
  with:
  - tox-uv
- name: twine
- name: virtualenv
- name: yt-dlp
