- name: ssh dir stat
  stat: path=~/.ssh
  register: ssh_dir

- name: ssh dir exists
  when: not ssh_dir.stat.exists
  file: path=~/.ssh
        state=directory

- name: ssh known_hosts contains github.com key
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    mode: 0644
    state: present
    line: "{{ lookup('file', 'github_ssh_host_key') }}"
    regexp: "^github\\.com "
