- name: remove old rubbish
  command: find ~/.Trash -mtime +30 -delete

- name: brew cleanup
  command: brew cleanup --prune 14

- name: uv cache prune
  command: uv cache prune --force
  register: uv_prune
  changed_when: "'Removed' in uv_prune.stderr"
  tags:
  - uv

- name: pip cache purge
  command: uvx pip cache purge

- name: pre-commit garbage collection
  command: pre-commit gc

- name: yarn cache clean
  command: yarn cache clean

- name: cargo cache clean
  command: cargo cache -a
